[theme]
base = "light"
primaryColor = "#875a7b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f5f5"
textColor = "#263332"
borderColor = "#dfe5e3"
baseRadius = "small"
buttonRadius = "small"

[theme.sidebar]
backgroundColor = "#eef3f1"
secondaryBackgroundColor = "#ffffff"
primaryColor = "#386b60"
textColor = "#263332"

[client]
toolbarMode = "minimal"
